/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Table service. Represents a row in the &quot;librarian_Table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link builder.model.impl.TableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link builder.model.impl.TableImpl}.
 * </p>
 *
 * @author Sasha
 * @see Table
 * @see builder.model.impl.TableImpl
 * @see builder.model.impl.TableModelImpl
 * @generated
 */
public interface TableModel extends BaseModel<Table> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a table model instance should use the {@link Table} interface instead.
	 */

	/**
	 * Returns the primary key of this table.
	 *
	 * @return the primary key of this table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this table.
	 *
	 * @param primaryKey the primary key of this table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the table ID of this table.
	 *
	 * @return the table ID of this table
	 */
	public long getTableId();

	/**
	 * Sets the table ID of this table.
	 *
	 * @param tableId the table ID of this table
	 */
	public void setTableId(long tableId);

	/**
	 * Returns the table book name of this table.
	 *
	 * @return the table book name of this table
	 */
	@AutoEscape
	public String getTableBookName();

	/**
	 * Sets the table book name of this table.
	 *
	 * @param tableBookName the table book name of this table
	 */
	public void setTableBookName(String tableBookName);

	/**
	 * Returns the table book description of this table.
	 *
	 * @return the table book description of this table
	 */
	@AutoEscape
	public String getTableBookDescription();

	/**
	 * Sets the table book description of this table.
	 *
	 * @param tableBookDescription the table book description of this table
	 */
	public void setTableBookDescription(String tableBookDescription);

	/**
	 * Returns the table author name of this table.
	 *
	 * @return the table author name of this table
	 */
	@AutoEscape
	public String getTableAuthorName();

	/**
	 * Sets the table author name of this table.
	 *
	 * @param tableAuthorName the table author name of this table
	 */
	public void setTableAuthorName(String tableAuthorName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(builder.model.Table table);

	@Override
	public int hashCode();

	@Override
	public CacheModel<builder.model.Table> toCacheModel();

	@Override
	public builder.model.Table toEscapedModel();

	@Override
	public builder.model.Table toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}